#pragma once

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define WS2812_DRIVER spi
#define WS2812_DI_PIN 16
#define WS2812_LED_COUNT 1
#define RGBLIGHT_LAYERS
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD
