#define LED_CAPS_LOCK_PIN GP25

#define WS2812_DI_PIN GP23
#define RGBLIGHT_LED_COUNT 1
#define RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_DEFAULT_MODE
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_EFFECT_BREATHING
